name = "DGAlgorithms"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["DGAlgorithms"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
pp.proofs.withType = false

[[require]]
name = "cslib"
scope = "leanprover"
rev = "stable"

[[lean_lib]]
name = "DGAlgorithms"
