name = "DGAlgorithms"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["DGAlgorithms"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
pp.proofs.withType = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.20.0-rc5"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[require]]
name = "«doc-gen4»"
git = "https://github.com/leanprover/doc-gen4"
rev = "v4.20.0-rc5"

[[require]]
name = "Canonical"
scope = "chasenorman"

[[lean_lib]]
name = "DGAlgorithms"
